[profile.default]
src = "src"
out = "out" 
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
build_info = true
extra_output = ["storageLayout"]

# L2-specific configurations
[profile.arbitrum]
eth_rpc_url = "${ARBITRUM_RPC_URL}"
etherscan_api_key = "${ARBISCAN_API_KEY}"
chain_id = 42161

[profile.optimism]
eth_rpc_url = "${OPTIMISM_RPC_URL}"
etherscan_api_key = "${OPTIMISTIC_ETHERSCAN_API_KEY}"
chain_id = 10

[profile.arbitrum_goerli]
eth_rpc_url = "${ARBITRUM_GOERLI_RPC_URL}"
etherscan_api_key = "${ARBISCAN_API_KEY}"
chain_id = 421613

# Gas optimizations for L2
[profile.production]
optimizer = true
optimizer_runs = 1000
via_ir = true

# Development settings
[profile.dev]
optimizer = false
verbosity = 3

# Testing configuration
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
